import java.awt.Frame;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author  Thewinator
 */
public class SettingsDialog extends javax.swing.JDialog {

    private IntVerifier intVer;

    private Frame parent;

    private boolean recursiveSave;

    /** Creates new form SettingsDialog */
    public SettingsDialog(java.awt.Frame parent, boolean forced) {
        super(parent, true);
        this.parent = parent;
        intVer = new IntVerifier();
        initComponents();
        txtPreviewFolder.setText(Settings.previewFolder);
        txtFlam3Folder.setText(Settings.flam3Folder);
        txtPreviewQuality.setText(Settings.previewQuality);
        txtPreviewFPS.setText(Integer.toString(Math.round(1000 / Settings.previewTimout)));
        this.bCancel.setEnabled(forced);
        recursiveSave = forced;
        setVisible(true);
        Debugger.appendAction("Opened SettingsDialog");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtPreviewFolder = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtPreviewQuality = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPreviewFPS = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txtFlam3Folder = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        bCancel = new javax.swing.JButton();
        bSave = new javax.swing.JButton();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Settings");
        setLocationByPlatform(true);
        setResizable(false);
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Temporary renders folder"));
        jLabel8.setText("Folder");
        txtPreviewFolder.setEditable(false);
        jButton3.setText("Browse");
        jButton3.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel1Layout.createSequentialGroup().addContainerGap().addComponent(jLabel8).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(txtPreviewFolder, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jButton3).addContainerGap()));
        jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel8).addComponent(jButton3).addComponent(txtPreviewFolder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)).addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Preview settings"));
        jLabel1.setText("Preview quality");
        txtPreviewQuality.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtPreviewQuality.setText("1");
        txtPreviewQuality.setInputVerifier(intVer);
        jLabel2.setText("Preview FPS");
        txtPreviewFPS.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtPreviewFPS.setText("25");
        txtPreviewFPS.setInputVerifier(intVer);
        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 11));
        jLabel3.setText("Note: this will greatly influence");
        jLabel4.setFont(new java.awt.Font("Tahoma", 2, 11));
        jLabel4.setText("the speed of the application");
        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel4Layout.createSequentialGroup().addContainerGap().addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel4Layout.createSequentialGroup().addComponent(jLabel2).addGap(24, 24, 24).addComponent(txtPreviewFPS, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)).addGroup(jPanel4Layout.createSequentialGroup().addComponent(jLabel1).addGap(10, 10, 10).addComponent(txtPreviewQuality, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jLabel4).addComponent(jLabel3)))).addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        jPanel4Layout.setVerticalGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel4Layout.createSequentialGroup().addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel2).addComponent(txtPreviewFPS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(txtPreviewQuality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jLabel3).addComponent(jLabel1)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jLabel4).addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("FLAM3 folder"));
        jLabel11.setText("Folder");
        txtFlam3Folder.setEditable(false);
        jButton6.setText("Browse");
        jButton6.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel5Layout.createSequentialGroup().addContainerGap().addComponent(jLabel11).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(txtFlam3Folder, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jButton6).addContainerGap()));
        jPanel5Layout.setVerticalGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel5Layout.createSequentialGroup().addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel11).addComponent(jButton6).addComponent(txtFlam3Folder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)).addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        bCancel.setText("Cancel");
        bCancel.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelActionPerformed(evt);
            }
        });
        bSave.setText("Save");
        bSave.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSaveActionPerformed(evt);
            }
        });
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addContainerGap().addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup().addComponent(bSave).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(bCancel))).addContainerGap()));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addContainerGap().addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(bCancel).addComponent(bSave)).addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        pack();
    }

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
        JFileChooser pickFile = new JFileChooser();
        pickFile.setCurrentDirectory(new File(txtPreviewFolder.getText()));
        pickFile.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int retVal = pickFile.showOpenDialog(super.getParent());
        if (retVal == JFileChooser.APPROVE_OPTION) {
            txtPreviewFolder.setText(pickFile.getSelectedFile().toString());
        }
    }

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {
        JFileChooser pickFile = new JFileChooser();
        pickFile.setCurrentDirectory(new File(txtFlam3Folder.getText()));
        pickFile.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int retVal = pickFile.showOpenDialog(super.getParent());
        if (retVal == JFileChooser.APPROVE_OPTION) {
            if (Utils.isValidFlam3Folder(pickFile.getSelectedFile().toString())) {
                txtFlam3Folder.setText(pickFile.getSelectedFile().toString());
            } else {
                JOptionPane.showMessageDialog(parent, "FLAM3 folder is missing essential files, please make sure the folder contains all FLAM3 files.", "Missing FLAM3 files", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    private void bCancelActionPerformed(java.awt.event.ActionEvent evt) {
        this.setVisible(false);
    }

    private void bSaveActionPerformed(java.awt.event.ActionEvent evt) {
        Settings.flam3Folder = this.txtFlam3Folder.getText();
        Settings.previewFolder = this.txtPreviewFolder.getText();
        Settings.previewTimout = Math.round(1000 / Integer.parseInt(this.txtPreviewFPS.getText()));
        Settings.previewQuality = this.txtPreviewQuality.getText();
        if (recursiveSave) {
            if (Settings.validate()) {
                Settings.saveSettings();
                this.setVisible(false);
            }
        } else {
            Settings.saveSettings();
            this.setVisible(false);
        }
    }

    private javax.swing.JButton bCancel;

    private javax.swing.JButton bSave;

    private javax.swing.JButton jButton3;

    private javax.swing.JButton jButton6;

    private javax.swing.JLabel jLabel1;

    private javax.swing.JLabel jLabel11;

    private javax.swing.JLabel jLabel2;

    private javax.swing.JLabel jLabel3;

    private javax.swing.JLabel jLabel4;

    private javax.swing.JLabel jLabel8;

    private javax.swing.JPanel jPanel1;

    private javax.swing.JPanel jPanel4;

    private javax.swing.JPanel jPanel5;

    private javax.swing.JTextField txtFlam3Folder;

    private javax.swing.JTextField txtPreviewFPS;

    private javax.swing.JTextField txtPreviewFolder;

    private javax.swing.JTextField txtPreviewQuality;
}
