package assfxmaker.lib.dialog;

import assfxmaker.lib.Language;

/**
 * <p>This is a dialog which display informations.<br />
 * C'est une boîte de dialogue qui montre des informations.</p>
 * @author The Wingate 2940
 */
public class AboutDialog extends javax.swing.JDialog {

    private Language localeLanguage;

    /** <p>Creates new form AboutDialog.<br />
     * Crée un nouveau formulaire AboutDialog.</p> */
    public AboutDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** <p>Set the language.<br />Définit le langage.</p> */
    public void setLanguageAndConfigure(Language lang) {
        localeLanguage = lang;
        if (lang.getValueOf("titleABT") != null) {
            setTitle(lang.getValueOf("titleABT"));
        }
        if (lang.getValueOf("messAbout") != null) {
            lblAFMMessage.setText(lang.getValueOf("messAbout"));
        }
        if (lang.getValueOf("messAssSketchpad") != null) {
            lblASPMessage.setText(lang.getValueOf("messAssSketchpad"));
        }
        if (lang.getValueOf("labelUsedByAFM") != null) {
            lblUsedByAFM.setText(lang.getValueOf("labelUsedByAFM"));
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        lblAssFxMaker = new javax.swing.JLabel();
        lblAFMMessage = new javax.swing.JLabel();
        lblAFMLink = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblAssSketchpad = new javax.swing.JLabel();
        lblASPMessage = new javax.swing.JLabel();
        lblASPLink = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblUsedByAFM = new javax.swing.JLabel();
        lblJRuby = new javax.swing.JLabel();
        lblCrystalClear = new javax.swing.JLabel();
        lblJSyntaxPane = new javax.swing.JLabel();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("About AssFxMaker");
        setAlwaysOnTop(true);
        addMouseListener(new java.awt.event.MouseAdapter() {

            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        jPanel1.setLayout(null);
        lblAssFxMaker.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assfxmaker/docs/Feuille 2.png")));
        lblAssFxMaker.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblAssFxMaker.addMouseListener(new java.awt.event.MouseAdapter() {

            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAssFxMakerMouseClicked(evt);
            }
        });
        jPanel1.add(lblAssFxMaker);
        lblAssFxMaker.setBounds(0, 0, 504, 254);
        lblAFMMessage.setText("<html><b>AssFxMaker</b> (a part of Funsub project 2006-2010)<br />Created using Netbeans, JDK, JRuby, Crystal Clear, JSyntaxPane.<br /><br />This software is under GNU/GPL license and is free. This is also a Charityware.");
        lblAFMMessage.addMouseListener(new java.awt.event.MouseAdapter() {

            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAFMMessageMouseClicked(evt);
            }
        });
        jPanel1.add(lblAFMMessage);
        lblAFMMessage.setBounds(10, 260, 490, 70);
        lblAFMLink.setForeground(new java.awt.Color(0, 0, 255));
        lblAFMLink.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assfxmaker/docs/20px-Crystal_Clear_app_internet.png")));
        lblAFMLink.setText("http://code.google.com/p/assfxmaker/");
        lblAFMLink.addMouseListener(new java.awt.event.MouseAdapter() {

            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAFMLinkMouseClicked(evt);
            }

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAFMLinkMouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAFMLinkMouseExited(evt);
            }
        });
        jPanel1.add(lblAFMLink);
        lblAFMLink.setBounds(10, 340, 490, 20);
        jTabbedPane1.addTab("AssFxMaker", jPanel1);
        jPanel2.setLayout(null);
        lblAssSketchpad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assfxmaker/docs/asssketchpad-about.png")));
        lblAssSketchpad.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblAssSketchpad.addMouseListener(new java.awt.event.MouseAdapter() {

            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAssSketchpadMouseClicked(evt);
            }
        });
        jPanel2.add(lblAssSketchpad);
        lblAssSketchpad.setBounds(0, 0, 504, 254);
        lblASPMessage.setText("<html>This software can create or edit drawings in ASS format.<br />It has been created to help those who want to use a drawing tool on Linux and Mac OS X.<br /><br />Evolution : ZDrawing -> ZDrawingLite -> AssSketchpad. (Funsub project)<br />This software is under GNU/GPLv3 licence, open and free to use, for all.");
        lblASPMessage.addMouseListener(new java.awt.event.MouseAdapter() {

            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblASPMessageMouseClicked(evt);
            }
        });
        jPanel2.add(lblASPMessage);
        lblASPMessage.setBounds(10, 260, 490, 80);
        lblASPLink.setForeground(new java.awt.Color(0, 0, 255));
        lblASPLink.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assfxmaker/docs/20px-Crystal_Clear_app_internet.png")));
        lblASPLink.setText("http://code.google.com/p/asssketchpad/");
        lblASPLink.addMouseListener(new java.awt.event.MouseAdapter() {

            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblASPLinkMouseClicked(evt);
            }

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblASPLinkMouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblASPLinkMouseExited(evt);
            }
        });
        jPanel2.add(lblASPLink);
        lblASPLink.setBounds(10, 350, 490, 20);
        jTabbedPane1.addTab("AssSketchpad", jPanel2);
        lblUsedByAFM.setText("Used by AssFxMaker : ");
        lblJRuby.setForeground(new java.awt.Color(0, 0, 255));
        lblJRuby.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assfxmaker/docs/20px-Crystal_Clear_app_internet.png")));
        lblJRuby.setText("JRuby - http://jruby.org/");
        lblJRuby.addMouseListener(new java.awt.event.MouseAdapter() {

            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblJRubyMouseClicked(evt);
            }

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblJRubyMouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblJRubyMouseExited(evt);
            }
        });
        lblCrystalClear.setForeground(new java.awt.Color(0, 0, 255));
        lblCrystalClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assfxmaker/docs/20px-Crystal_Clear_app_internet.png")));
        lblCrystalClear.setText("Crystal Clear - http://commons.wikimedia.org/wiki/Crystal_Clear");
        lblCrystalClear.addMouseListener(new java.awt.event.MouseAdapter() {

            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCrystalClearMouseClicked(evt);
            }

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCrystalClearMouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCrystalClearMouseExited(evt);
            }
        });
        lblJSyntaxPane.setForeground(new java.awt.Color(0, 0, 255));
        lblJSyntaxPane.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assfxmaker/docs/20px-Crystal_Clear_app_internet.png")));
        lblJSyntaxPane.setText("JSyntaxePane - http://code.google.com/p/jsyntaxpane/");
        lblJSyntaxPane.addMouseListener(new java.awt.event.MouseAdapter() {

            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblJSyntaxPaneMouseClicked(evt);
            }

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblJSyntaxPaneMouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblJSyntaxPaneMouseExited(evt);
            }
        });
        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel3Layout.createSequentialGroup().addContainerGap().addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(lblUsedByAFM).addGroup(jPanel3Layout.createSequentialGroup().addGap(10, 10, 10).addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(lblCrystalClear).addComponent(lblJRuby, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE).addComponent(lblJSyntaxPane)))).addContainerGap()));
        jPanel3Layout.setVerticalGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel3Layout.createSequentialGroup().addContainerGap().addComponent(lblUsedByAFM).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(lblJRuby).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(lblCrystalClear).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(lblJSyntaxPane).addContainerGap(285, Short.MAX_VALUE)));
        jTabbedPane1.addTab("+", jPanel3);
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE));
        pack();
    }

    private void lblAFMMessageMouseClicked(java.awt.event.MouseEvent evt) {
        dispose();
    }

    private void lblAssFxMakerMouseClicked(java.awt.event.MouseEvent evt) {
        dispose();
    }

    private void formMouseClicked(java.awt.event.MouseEvent evt) {
        dispose();
    }

    private void lblAFMLinkMouseClicked(java.awt.event.MouseEvent evt) {
        launchLink("http://code.google.com/p/assfxmaker/");
    }

    private void lblAssSketchpadMouseClicked(java.awt.event.MouseEvent evt) {
        dispose();
    }

    private void lblASPMessageMouseClicked(java.awt.event.MouseEvent evt) {
        dispose();
    }

    private void lblASPLinkMouseClicked(java.awt.event.MouseEvent evt) {
        launchLink("http://code.google.com/p/asssketchpad/");
    }

    private void lblJRubyMouseClicked(java.awt.event.MouseEvent evt) {
        launchLink("http://jruby.org/");
    }

    private void lblCrystalClearMouseClicked(java.awt.event.MouseEvent evt) {
        launchLink("http://commons.wikimedia.org/wiki/Crystal_Clear");
    }

    private void lblJSyntaxPaneMouseClicked(java.awt.event.MouseEvent evt) {
        launchLink("http://code.google.com/p/jsyntaxpane/");
    }

    private void lblAFMLinkMouseEntered(java.awt.event.MouseEvent evt) {
        lblAFMLink.setText("<html><u>http://code.google.com/p/assfxmaker/");
    }

    private void lblAFMLinkMouseExited(java.awt.event.MouseEvent evt) {
        lblAFMLink.setText("http://code.google.com/p/assfxmaker/");
    }

    private void lblASPLinkMouseEntered(java.awt.event.MouseEvent evt) {
        lblASPLink.setText("<html><u>http://code.google.com/p/asssketchpad/");
    }

    private void lblASPLinkMouseExited(java.awt.event.MouseEvent evt) {
        lblASPLink.setText("http://code.google.com/p/asssketchpad/");
    }

    private void lblJRubyMouseEntered(java.awt.event.MouseEvent evt) {
        lblJRuby.setText("<html>JRuby - <u>http://jruby.org/");
    }

    private void lblJRubyMouseExited(java.awt.event.MouseEvent evt) {
        lblJRuby.setText("JRuby - http://jruby.org/");
    }

    private void lblCrystalClearMouseEntered(java.awt.event.MouseEvent evt) {
        lblCrystalClear.setText("<html>Crystal Clear - <u>http://commons.wikimedia.org/wiki/Crystal_Clear");
    }

    private void lblCrystalClearMouseExited(java.awt.event.MouseEvent evt) {
        lblCrystalClear.setText("Crystal Clear - http://commons.wikimedia.org/wiki/Crystal_Clear");
    }

    private void lblJSyntaxPaneMouseEntered(java.awt.event.MouseEvent evt) {
        lblJSyntaxPane.setText("<html>JSyntaxePane - <u>http://code.google.com/p/jsyntaxpane/");
    }

    private void lblJSyntaxPaneMouseExited(java.awt.event.MouseEvent evt) {
        lblJSyntaxPane.setText("JSyntaxePane - http://code.google.com/p/jsyntaxpane/");
    }

    /** <p>Launch the selected link and open a browser.<br />
     * Lance le lien sélectionné et ou un navigateur.</p> */
    private void launchLink(String link) {
        boolean hasResult = true;
        if (java.awt.Desktop.isDesktopSupported()) {
            java.awt.Desktop desktop = java.awt.Desktop.getDesktop();
            if (desktop.isSupported(java.awt.Desktop.Action.BROWSE)) {
                try {
                    try {
                        desktop.browse(new java.net.URI(link));
                    } catch (java.io.IOException ex) {
                        hasResult = false;
                    }
                } catch (java.net.URISyntaxException ex) {
                    hasResult = false;
                }
            } else {
                hasResult = false;
            }
        } else {
            hasResult = false;
        }
        if (hasResult == false) {
            java.util.Properties sys = System.getProperties();
            String os = sys.getProperty("os.name").toLowerCase();
            try {
                if (os.contains("windows") == true) {
                    Process proc = Runtime.getRuntime().exec("cmd /c start " + link);
                } else {
                    Process proc = Runtime.getRuntime().exec("start " + link);
                }
            } catch (java.io.IOException e) {
            }
        }
    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                AboutDialog dialog = new AboutDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    private javax.swing.JPanel jPanel1;

    private javax.swing.JPanel jPanel2;

    private javax.swing.JPanel jPanel3;

    private javax.swing.JTabbedPane jTabbedPane1;

    private javax.swing.JLabel lblAFMLink;

    private javax.swing.JLabel lblAFMMessage;

    private javax.swing.JLabel lblASPLink;

    private javax.swing.JLabel lblASPMessage;

    private javax.swing.JLabel lblAssFxMaker;

    private javax.swing.JLabel lblAssSketchpad;

    private javax.swing.JLabel lblCrystalClear;

    private javax.swing.JLabel lblJRuby;

    private javax.swing.JLabel lblJSyntaxPane;

    private javax.swing.JLabel lblUsedByAFM;
}
