package assfxmaker.lib.dialog;

import assfxmaker.lib.Language;
import java.io.IOException;
import java.net.URISyntaxException;

/**
 * <p>This is a dialog for information about JRuby and Java.<br />
 * C'est une boîte de dialogue qui informe sur JRuby et Java..</p>
 * @author The Wingate 2940
 */
public class OnLineHelpDialog extends javax.swing.JDialog {

    private ButtonPressed bp;

    private Language localeLanguage;

    public enum ButtonPressed {

        NONE, OK_BUTTON, CANCEL_BUTTON
    }

    /** <p>Creates new form OnLineHelpDialog.<br />
     * Crée un nouveau formulaire OnLineHelpDialog.</p> */
    public OnLineHelpDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        lblJavaSun = new javax.swing.JLabel();
        lblRubyLang = new javax.swing.JLabel();
        lblRubyProg = new javax.swing.JLabel();
        lblRubyDoc = new javax.swing.JLabel();
        lblJRuby = new javax.swing.JLabel();
        Close_Button = new javax.swing.JButton();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Online help...");
        setResizable(false);
        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel1.setText(" Here are tools and resources you can use to have more skills dealing with scripts using Java and Ruby (or JRuby) : ");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jLabel1.setOpaque(true);
        lblJavaSun.setForeground(java.awt.Color.blue);
        lblJavaSun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assfxmaker/docs/20px-Crystal_Clear_app_internet.png")));
        lblJavaSun.setText("<html>Java - Oracle : http://www.oracle.com/technetwork/java/index.html");
        lblJavaSun.addMouseListener(new java.awt.event.MouseAdapter() {

            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblJavaSunMouseClicked(evt);
            }

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblJavaSunMouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblJavaSunMouseExited(evt);
            }
        });
        lblRubyLang.setForeground(java.awt.Color.blue);
        lblRubyLang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assfxmaker/docs/20px-Crystal_Clear_app_internet.png")));
        lblRubyLang.setText("<html>Ruby - A programmer's best friend : http://www.ruby-lang.org");
        lblRubyLang.addMouseListener(new java.awt.event.MouseAdapter() {

            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRubyLangMouseClicked(evt);
            }

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblRubyLangMouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblRubyLangMouseExited(evt);
            }
        });
        lblRubyProg.setForeground(java.awt.Color.blue);
        lblRubyProg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assfxmaker/docs/20px-Crystal_Clear_app_internet.png")));
        lblRubyProg.setText("<html>Ruby - Programming Ruby : http://www.ruby-doc.org/docs/ProgrammingRuby/");
        lblRubyProg.addMouseListener(new java.awt.event.MouseAdapter() {

            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRubyProgMouseClicked(evt);
            }

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblRubyProgMouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblRubyProgMouseExited(evt);
            }
        });
        lblRubyDoc.setForeground(java.awt.Color.blue);
        lblRubyDoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assfxmaker/docs/20px-Crystal_Clear_app_internet.png")));
        lblRubyDoc.setText("<html>Ruby - Ruby-Doc.org : http://www.ruby-doc.org/");
        lblRubyDoc.addMouseListener(new java.awt.event.MouseAdapter() {

            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRubyDocMouseClicked(evt);
            }

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblRubyDocMouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblRubyDocMouseExited(evt);
            }
        });
        lblJRuby.setForeground(java.awt.Color.blue);
        lblJRuby.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assfxmaker/docs/20px-Crystal_Clear_app_internet.png")));
        lblJRuby.setText("<html>JRuby - JRuby : http://jruby.org/");
        lblJRuby.addMouseListener(new java.awt.event.MouseAdapter() {

            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblJRubyMouseClicked(evt);
            }

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblJRubyMouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblJRubyMouseExited(evt);
            }
        });
        Close_Button.setText("Close");
        Close_Button.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Close_ButtonActionPerformed(evt);
            }
        });
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addContainerGap().addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 714, Short.MAX_VALUE).addComponent(lblJavaSun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(lblRubyLang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(lblRubyProg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(lblRubyDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(lblJRuby, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(Close_Button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)).addContainerGap()));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addContainerGap().addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(lblJavaSun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(lblRubyLang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(lblRubyProg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(lblRubyDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(lblJRuby, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(Close_Button).addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        pack();
    }

    private void Close_ButtonActionPerformed(java.awt.event.ActionEvent evt) {
        bp = ButtonPressed.OK_BUTTON;
        dispose();
    }

    private void lblJavaSunMouseClicked(java.awt.event.MouseEvent evt) {
        launchLink("http://www.oracle.com/technetwork/java/index.html");
    }

    private void lblRubyLangMouseClicked(java.awt.event.MouseEvent evt) {
        launchLink("http://www.ruby-lang.org");
    }

    private void lblRubyProgMouseClicked(java.awt.event.MouseEvent evt) {
        launchLink("http://www.ruby-doc.org/docs/ProgrammingRuby/");
    }

    private void lblRubyDocMouseClicked(java.awt.event.MouseEvent evt) {
        launchLink("http://www.ruby-doc.org/");
    }

    private void lblJRubyMouseClicked(java.awt.event.MouseEvent evt) {
        launchLink("http://jruby.org/");
    }

    private void lblJavaSunMouseEntered(java.awt.event.MouseEvent evt) {
        lblJavaSun.setText("<html>Java - Oracle : <u>http://www.oracle.com/technetwork/java/index.html");
    }

    private void lblJavaSunMouseExited(java.awt.event.MouseEvent evt) {
        lblJavaSun.setText("<html>Java - Oracle : http://www.oracle.com/technetwork/java/index.html");
    }

    private void lblRubyLangMouseEntered(java.awt.event.MouseEvent evt) {
        lblRubyLang.setText("<html>Ruby - A programmer's best friend : <u>http://www.ruby-lang.org");
    }

    private void lblRubyLangMouseExited(java.awt.event.MouseEvent evt) {
        lblRubyLang.setText("<html>Ruby - A programmer's best friend : http://www.ruby-lang.org");
    }

    private void lblRubyProgMouseEntered(java.awt.event.MouseEvent evt) {
        lblRubyProg.setText("<html>Ruby - Programming Ruby : <u>http://www.ruby-doc.org/docs/ProgrammingRuby/");
    }

    private void lblRubyProgMouseExited(java.awt.event.MouseEvent evt) {
        lblRubyProg.setText("<html>Ruby - Programming Ruby : http://www.ruby-doc.org/docs/ProgrammingRuby/");
    }

    private void lblRubyDocMouseEntered(java.awt.event.MouseEvent evt) {
        lblRubyDoc.setText("<html>Ruby - Ruby-Doc.org : <u>http://www.ruby-doc.org/");
    }

    private void lblRubyDocMouseExited(java.awt.event.MouseEvent evt) {
        lblRubyDoc.setText("<html>Ruby - Ruby-Doc.org : http://www.ruby-doc.org/");
    }

    private void lblJRubyMouseEntered(java.awt.event.MouseEvent evt) {
        lblJRuby.setText("<html>JRuby - JRuby : <u>http://jruby.org/");
    }

    private void lblJRubyMouseExited(java.awt.event.MouseEvent evt) {
        lblJRuby.setText("<html>JRuby - JRuby : http://jruby.org/");
    }

    /** <p>Show the dialog.<br />
     * Montre la dialogue.</p> */
    public boolean showDialog() {
        setVisible(true);
        if (bp.equals(ButtonPressed.OK_BUTTON)) {
            return true;
        } else {
            return false;
        }
    }

    /** <p>Launch the selected link and open a browser.<br />
     * Lance le lien sélectionné et ou un navigateur.</p> */
    private void launchLink(String link) {
        boolean hasResult = true;
        if (java.awt.Desktop.isDesktopSupported()) {
            java.awt.Desktop desktop = java.awt.Desktop.getDesktop();
            if (desktop.isSupported(java.awt.Desktop.Action.BROWSE)) {
                try {
                    try {
                        desktop.browse(new java.net.URI(link));
                    } catch (IOException ex) {
                        hasResult = false;
                    }
                } catch (URISyntaxException ex) {
                    hasResult = false;
                }
            } else {
                hasResult = false;
            }
        } else {
            hasResult = false;
        }
        if (hasResult == false) {
            java.util.Properties sys = System.getProperties();
            String os = sys.getProperty("os.name").toLowerCase();
            try {
                if (os.contains("windows") == true) {
                    Process proc = Runtime.getRuntime().exec("cmd /c start " + link);
                } else {
                    Process proc = Runtime.getRuntime().exec("start " + link);
                }
            } catch (java.io.IOException e) {
            }
        }
    }

    /** <p>Set the language.<br />Définit le langage.</p> */
    public void setLanguageAndConfigure(Language lang) {
        localeLanguage = lang;
        if (lang.getValueOf("titleOHD") != null) {
            setTitle(lang.getValueOf("titleOHD"));
        }
        if (lang.getValueOf("buttonClose") != null) {
            Close_Button.setText(lang.getValueOf("buttonClose"));
        }
        if (lang.getValueOf("messTools") != null) {
            jLabel1.setText(lang.getValueOf("messTools"));
        }
    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                OnLineHelpDialog dialog = new OnLineHelpDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    private javax.swing.JButton Close_Button;

    private javax.swing.JLabel jLabel1;

    private javax.swing.JLabel lblJRuby;

    private javax.swing.JLabel lblJavaSun;

    private javax.swing.JLabel lblRubyDoc;

    private javax.swing.JLabel lblRubyLang;

    private javax.swing.JLabel lblRubyProg;
}
