package gui;

import jabber.JabberChat;
import java.awt.Cursor;
import java.awt.Frame;
import org.jivesoftware.smack.XMPPException;
import javax.swing.*;
import java.net.URI;
import java.awt.Desktop;
import java.io.IOException;
import java.net.URISyntaxException;

/**
 *
 * @author John Gu
 */
public class LoginDialog extends javax.swing.JDialog {

    private JabberChat connection;

    public boolean isLoggedIn = false;

    private Frame buddyListParent;

    private Task task;

    /** Creates new form LoginDialog */
    public LoginDialog(java.awt.Frame parent, boolean modal, JabberChat c) {
        super(parent, modal);
        initComponents();
        this.setTitle("Login");
        connection = c;
        isLoggedIn = false;
        buddyListParent = parent;
        loginProgress.setVisible(false);
        loginProgress.setIndeterminate(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {
        LoginButton = new javax.swing.JButton();
        CloseButton = new javax.swing.JButton();
        ErrorText = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        PasswordBox = new javax.swing.JPasswordField();
        UserNameBox = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        register = new javax.swing.JLabel();
        loginProgress = new javax.swing.JProgressBar();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        LoginButton.setText("Login");
        LoginButton.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });
        CloseButton.setText("Cancel");
        CloseButton.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseButtonActionPerformed(evt);
            }
        });
        ErrorText.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setFont(new java.awt.Font("Papyrus", 1, 14));
        jLabel1.setText("User Name");
        jLabel2.setFont(new java.awt.Font("Papyrus", 1, 14));
        jLabel2.setText("Password");
        PasswordBox.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordBoxActionPerformed(evt);
            }
        });
        PasswordBox.addFocusListener(new java.awt.event.FocusAdapter() {

            public void focusGained(java.awt.event.FocusEvent evt) {
                PasswordBoxFocusGained(evt);
            }
        });
        UserNameBox.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserNameBoxActionPerformed(evt);
            }
        });
        UserNameBox.addFocusListener(new java.awt.event.FocusAdapter() {

            public void focusGained(java.awt.event.FocusEvent evt) {
                UserNameBoxFocusGained(evt);
            }
        });
        jLabel3.setFont(new java.awt.Font("Papyrus", 0, 14));
        jLabel3.setText("@jabber.org");
        register.setFont(new java.awt.Font("Tahoma", 0, 10));
        register.setText("<html>Don't have an account?  Click here to <font color=blue><i><u><a>register</a></u></i></font>.</html>");
        register.addMouseListener(new java.awt.event.MouseAdapter() {

            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerMouseClicked(evt);
            }

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registerMouseEntered(evt);
            }
        });
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addContainerGap().addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jLabel1).addComponent(PasswordBox, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE).addComponent(register, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE).addGroup(layout.createSequentialGroup().addComponent(LoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE).addComponent(CloseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)).addComponent(ErrorText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE).addGroup(layout.createSequentialGroup().addComponent(UserNameBox, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE).addComponent(jLabel3)).addComponent(loginProgress, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE).addComponent(jLabel2)).addContainerGap()));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup().addContainerGap().addComponent(jLabel1).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(UserNameBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)).addGap(18, 18, 18).addComponent(jLabel2).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(PasswordBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(ErrorText, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE).addGap(13, 13, 13).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(LoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(CloseButton, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(register).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(loginProgress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addContainerGap()));
        pack();
    }

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {
        setCursor(new Cursor(Cursor.WAIT_CURSOR));
        loginProgress.setVisible(true);
        ErrorText.setText("Logging in ... ");
        task = new Task();
        task.execute();
    }

    private void CloseButtonActionPerformed(java.awt.event.ActionEvent evt) {
        PasswordBox.setText("");
        LoginButton.setEnabled(true);
        this.dispose();
    }

    private void PasswordBoxActionPerformed(java.awt.event.ActionEvent evt) {
        LoginButton.doClick();
    }

    private void PasswordBoxFocusGained(java.awt.event.FocusEvent evt) {
        ErrorText.setText("");
    }

    private void UserNameBoxActionPerformed(java.awt.event.ActionEvent evt) {
        LoginButton.doClick();
    }

    private void UserNameBoxFocusGained(java.awt.event.FocusEvent evt) {
        ErrorText.setText("");
    }

    private void registerMouseClicked(java.awt.event.MouseEvent evt) {
        String url = "http://register.jabber.org/";
        if (Desktop.isDesktopSupported()) {
            Desktop desk = Desktop.getDesktop();
            if (desk.isSupported(Desktop.Action.BROWSE)) {
                try {
                    URI account = new URI(url);
                    desk.browse(account);
                } catch (IOException e) {
                    JOptionPane.showMessageDialog(rootPane, "Cannot open http://register.jabber.org.  You don't have a registered application for browsing.");
                } catch (URISyntaxException e) {
                    JOptionPane.showMessageDialog(rootPane, "An unexpected error has occurred\n" + e.getMessage());
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Cannot open http://register.jabber.org.  Please visit the site manually.");
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Cannot open http://register.jabber.org.  Please visit the site manually.");
        }
    }

    private void registerMouseEntered(java.awt.event.MouseEvent evt) {
        register.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }

    private void Login() {
        String user = UserNameBox.getText();
        String password = new String(PasswordBox.getPassword());
        if (user.equals("") || password.equals("")) {
            ErrorText.setText("Wrong username or password. Please try again.");
            return;
        }
        try {
            connection.Login(user, password);
            isLoggedIn = true;
            ErrorText.setText("");
            this.dispose();
        } catch (XMPPException e) {
            ErrorText.setText("Wrong username or password. Please try again.");
            PasswordBox.setText("");
        }
    }

    class Task extends SwingWorker<Void, Void> {

        @Override
        public Void doInBackground() {
            Login();
            return null;
        }

        @Override
        public void done() {
            loginProgress.setVisible(false);
            buddyListParent.setVisible(true);
            PasswordBox.setText("");
            LoginButton.setEnabled(true);
            setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        }
    }

    private javax.swing.JButton CloseButton;

    private javax.swing.JLabel ErrorText;

    private javax.swing.JButton LoginButton;

    private javax.swing.JPasswordField PasswordBox;

    private javax.swing.JTextField UserNameBox;

    private javax.swing.JLabel jLabel1;

    private javax.swing.JLabel jLabel2;

    private javax.swing.JLabel jLabel3;

    private javax.swing.JProgressBar loginProgress;

    private javax.swing.JLabel register;
}
