package jjsplit;

import java.awt.Desktop;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 * LICENSE: PUBLIC DOMAIN
 * @author vigneshwaran
 * Email: vigneshwaran2007@gmail.com
 *
 * translation to czech language: martinprucha
 * Email: prucha.martin@gmail.com
 */
public class JJSplit extends javax.swing.JFrame {

    private File joinerInputFile;

    private File joinerOutputFile;

    private String joinerOutputFileName;

    private File splitterInputFile = null;

    private File splitterOutputFile = null;

    private int noofparts = 2;

    private long splitsize;

    private long filesize;

    private boolean deleteFileAfterSplit = false;

    private boolean deleteFilesAfterJoin = false;

    /** Creates new form JJSplit */
    public JJSplit() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {
        buttonGroup1 = new javax.swing.ButtonGroup();
        topPanel = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        version = new javax.swing.JLabel();
        topDescription = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        joinerPanel = new javax.swing.JPanel();
        joinerSelectFilePanel = new javax.swing.JPanel();
        joinerInputFileTextField = new javax.swing.JTextField();
        joinerOutputFileTextField = new javax.swing.JTextField();
        joinerSelectFileButton = new javax.swing.JButton();
        joinerSelectOutputDirButton = new javax.swing.JButton();
        joinerProgressBar = new javax.swing.JProgressBar();
        joinerJoinButton = new javax.swing.JButton();
        joinerCancelButton = new javax.swing.JButton();
        joinerCheckBox = new javax.swing.JCheckBox();
        splitterPanel = new javax.swing.JPanel();
        splitterSelectFilePanel = new javax.swing.JPanel();
        splitterInputFileTextField = new javax.swing.JTextField();
        splitterOutputFileTextField = new javax.swing.JTextField();
        splitterSelectFileButton = new javax.swing.JButton();
        splitterSelectOutputDirButton = new javax.swing.JButton();
        splitterCheckBox = new javax.swing.JCheckBox();
        splitterProgressBar = new javax.swing.JProgressBar();
        splitterSplitButton = new javax.swing.JButton();
        splitterCancelButton = new javax.swing.JButton();
        partsRadioButton = new javax.swing.JRadioButton();
        sizeRadioButton = new javax.swing.JRadioButton();
        noofpartsTextField = new javax.swing.JTextField();
        splitSizeTextField = new javax.swing.JTextField();
        splitSizeComboBox = new javax.swing.JComboBox();
        aboutPanel = new javax.swing.JPanel();
        aboutLabel = new javax.swing.JLabel();
        aboutProductPanel = new javax.swing.JPanel();
        aboutLogo = new javax.swing.JLabel();
        aboutJJSplitLabel = new javax.swing.JLabel();
        aboutVersionLabel = new javax.swing.JLabel();
        aboutLicenceLabel = new javax.swing.JLabel();
        aboutDescLabel = new javax.swing.JLabel();
        aboutProductSiteLabel = new javax.swing.JLabel();
        aboutAuthorLabel = new javax.swing.JPanel();
        aboutNameLabel = new javax.swing.JLabel();
        aboutEmailLabel = new javax.swing.JLabel();
        aboutTwitterLabel = new javax.swing.JLabel();
        aboutMyName = new javax.swing.JLabel();
        aboutMyEmail = new javax.swing.JLabel();
        aboutMyTwitter = new javax.swing.JLabel();
        translationPanel = new javax.swing.JPanel();
        translationNameLabel = new javax.swing.JLabel();
        translationEmailLabel = new javax.swing.JLabel();
        statusPanel = new javax.swing.JPanel();
        status = new javax.swing.JLabel();
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JJSplit");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/jjsplit/resources/appicon.png")));
        topPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jjsplit/resources/smalllogo.png")));
        logo.setToolTipText("Open Source File Splitter and Joiner");
        logo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        titleLabel.setFont(new java.awt.Font("Harlow Solid Italic", 1, 36));
        titleLabel.setForeground(new java.awt.Color(51, 51, 51));
        titleLabel.setText("JJSplit");
        titleLabel.setToolTipText("Open Source File Splitter and Joiner");
        titleLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        version.setFont(new java.awt.Font("Agency FB", 3, 24));
        version.setForeground(new java.awt.Color(102, 102, 102));
        version.setText("v 1.23");
        version.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        topDescription.setFont(new java.awt.Font("Tahoma", 2, 11));
        topDescription.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        topDescription.setText("<html>#Open Source rozdělovač a slučovač souborů;<br><a href=http://jjsplit.sf.net>http://jjsplit.sf.net</a></html>");
        topDescription.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(topPanelLayout.createSequentialGroup().addContainerGap().addComponent(logo).addGap(18, 18, 18).addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(version, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 205, Short.MAX_VALUE).addComponent(topDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addContainerGap()));
        topPanelLayout.setVerticalGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(topPanelLayout.createSequentialGroup().addContainerGap().addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addGroup(topPanelLayout.createSequentialGroup().addComponent(topDescription, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE).addGap(15, 15, 15)).addComponent(logo, javax.swing.GroupLayout.Alignment.LEADING).addComponent(titleLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE).addComponent(version)).addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        joinerSelectFilePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Výběr souborů"));
        joinerInputFileTextField.setEditable(false);
        joinerInputFileTextField.setToolTipText("Select the .v1 file or .001 file to join..");
        joinerInputFileTextField.addMouseListener(new java.awt.event.MouseAdapter() {

            public void mouseClicked(java.awt.event.MouseEvent evt) {
                joinerInputFileTextFieldMouseClicked(evt);
            }
        });
        joinerOutputFileTextField.setEditable(false);
        joinerOutputFileTextField.setToolTipText("Click to change the output directory if you want.");
        joinerOutputFileTextField.addMouseListener(new java.awt.event.MouseAdapter() {

            public void mouseClicked(java.awt.event.MouseEvent evt) {
                joinerOutputFileTextFieldMouseClicked(evt);
            }
        });
        joinerSelectFileButton.setText("Vybrat první část");
        joinerSelectFileButton.setToolTipText("Select the .v1 file or .001 file to join..");
        joinerSelectFileButton.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                joinerSelectFileButtonActionPerformed(evt);
            }
        });
        joinerSelectOutputDirButton.setText("Vybrat výstupní adresář");
        joinerSelectOutputDirButton.setToolTipText("Click to change the output directory if you want.");
        joinerSelectOutputDirButton.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                joinerSelectOutputDirButtonActionPerformed(evt);
            }
        });
        javax.swing.GroupLayout joinerSelectFilePanelLayout = new javax.swing.GroupLayout(joinerSelectFilePanel);
        joinerSelectFilePanel.setLayout(joinerSelectFilePanelLayout);
        joinerSelectFilePanelLayout.setHorizontalGroup(joinerSelectFilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(joinerSelectFilePanelLayout.createSequentialGroup().addContainerGap().addGroup(joinerSelectFilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(joinerInputFileTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE).addComponent(joinerOutputFileTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(joinerSelectFilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false).addComponent(joinerSelectFileButton, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE).addComponent(joinerSelectOutputDirButton, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)).addContainerGap()));
        joinerSelectFilePanelLayout.setVerticalGroup(joinerSelectFilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(joinerSelectFilePanelLayout.createSequentialGroup().addContainerGap().addGroup(joinerSelectFilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(joinerInputFileTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(joinerSelectFileButton)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(joinerSelectFilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(joinerOutputFileTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(joinerSelectOutputDirButton)).addContainerGap(35, Short.MAX_VALUE)));
        joinerProgressBar.setStringPainted(true);
        joinerJoinButton.setText("Sloučit");
        joinerJoinButton.setToolTipText("Click to start joining process.");
        joinerJoinButton.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                joinerJoinButtonActionPerformed(evt);
            }
        });
        joinerCancelButton.setText("Cancel");
        joinerCancelButton.setToolTipText("Click to stop all processes and exit.");
        joinerCancelButton.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                joinerCancelButtonActionPerformed(evt);
            }
        });
        joinerCheckBox.setText("Delete parts while joining");
        joinerCheckBox.setToolTipText("Deleted permanently. Cannot be recovered.");
        javax.swing.GroupLayout joinerPanelLayout = new javax.swing.GroupLayout(joinerPanel);
        joinerPanel.setLayout(joinerPanelLayout);
        joinerPanelLayout.setHorizontalGroup(joinerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(joinerPanelLayout.createSequentialGroup().addContainerGap().addGroup(joinerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(joinerCheckBox).addComponent(joinerProgressBar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 625, Short.MAX_VALUE).addComponent(joinerSelectFilePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addGroup(javax.swing.GroupLayout.Alignment.TRAILING, joinerPanelLayout.createSequentialGroup().addComponent(joinerJoinButton).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(joinerCancelButton))).addContainerGap()));
        joinerPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] { joinerCancelButton, joinerJoinButton });
        joinerPanelLayout.setVerticalGroup(joinerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(joinerPanelLayout.createSequentialGroup().addContainerGap().addComponent(joinerSelectFilePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addGap(18, 18, 18).addComponent(joinerProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addGap(18, 18, 18).addGroup(joinerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(joinerJoinButton).addComponent(joinerCancelButton)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE).addComponent(joinerCheckBox).addContainerGap()));
        jTabbedPane1.addTab("<html><br /><br />Slučovač<br /><br />&nbsp;</html>", joinerPanel);
        splitterSelectFilePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Výběr souborů"));
        splitterInputFileTextField.setEditable(false);
        splitterInputFileTextField.setToolTipText("Select the input file to split.");
        splitterInputFileTextField.addMouseListener(new java.awt.event.MouseAdapter() {

            public void mouseClicked(java.awt.event.MouseEvent evt) {
                splitterInputFileTextFieldMouseClicked(evt);
            }
        });
        splitterOutputFileTextField.setEditable(false);
        splitterOutputFileTextField.setToolTipText("Click to change the output directory if you want.");
        splitterOutputFileTextField.addMouseListener(new java.awt.event.MouseAdapter() {

            public void mouseClicked(java.awt.event.MouseEvent evt) {
                splitterOutputFileTextFieldMouseClicked(evt);
            }
        });
        splitterSelectFileButton.setText("Vybrat soubor");
        splitterSelectFileButton.setToolTipText("Select the input file to split.");
        splitterSelectFileButton.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                splitterSelectFileButtonActionPerformed(evt);
            }
        });
        splitterSelectOutputDirButton.setText("Vybrat výstupní adresář");
        splitterSelectOutputDirButton.setToolTipText("Click to change the output directory if you want.");
        splitterSelectOutputDirButton.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                splitterSelectOutputDirButtonActionPerformed(evt);
            }
        });
        javax.swing.GroupLayout splitterSelectFilePanelLayout = new javax.swing.GroupLayout(splitterSelectFilePanel);
        splitterSelectFilePanel.setLayout(splitterSelectFilePanelLayout);
        splitterSelectFilePanelLayout.setHorizontalGroup(splitterSelectFilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(splitterSelectFilePanelLayout.createSequentialGroup().addContainerGap().addGroup(splitterSelectFilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(splitterInputFileTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE).addComponent(splitterOutputFileTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addGroup(splitterSelectFilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false).addComponent(splitterSelectOutputDirButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addComponent(splitterSelectFileButton, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)).addContainerGap()));
        splitterSelectFilePanelLayout.setVerticalGroup(splitterSelectFilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(splitterSelectFilePanelLayout.createSequentialGroup().addContainerGap().addGroup(splitterSelectFilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(splitterInputFileTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(splitterSelectFileButton)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(splitterSelectFilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(splitterOutputFileTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(splitterSelectOutputDirButton)).addContainerGap(37, Short.MAX_VALUE)));
        splitterCheckBox.setText("Smazat původní soubor po ukončení rozdělování");
        splitterCheckBox.setToolTipText("Deleted permanently. Cannot be recovered.");
        splitterProgressBar.setStringPainted(true);
        splitterSplitButton.setText("Rozdělit");
        splitterSplitButton.setToolTipText("Click to start the splitting process.");
        splitterSplitButton.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                splitterSplitButtonActionPerformed(evt);
            }
        });
        splitterCancelButton.setText("Storno");
        splitterCancelButton.setToolTipText("Click to stop all processes and exit.");
        splitterCancelButton.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                splitterCancelButtonActionPerformed(evt);
            }
        });
        buttonGroup1.add(partsRadioButton);
        partsRadioButton.setSelected(true);
        partsRadioButton.setText("Vybrat počet částí:");
        partsRadioButton.setToolTipText("Split the file into certain no of parts.");
        partsRadioButton.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                partsRadioButtonActionPerformed(evt);
            }
        });
        buttonGroup1.add(sizeRadioButton);
        sizeRadioButton.setText("Rozdělit soubor do částí velikosti:");
        sizeRadioButton.setToolTipText("Split the file into parts of certain size.");
        sizeRadioButton.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sizeRadioButtonActionPerformed(evt);
            }
        });
        noofpartsTextField.setText("2");
        noofpartsTextField.setToolTipText("Split the file into certain no of parts.");
        noofpartsTextField.addKeyListener(new java.awt.event.KeyAdapter() {

            public void keyTyped(java.awt.event.KeyEvent evt) {
                noofpartsTextFieldKeyTyped(evt);
            }
        });
        splitSizeTextField.setText("0");
        splitSizeTextField.setToolTipText("Split the file into parts of certain size.");
        splitSizeTextField.setEnabled(false);
        splitSizeTextField.addKeyListener(new java.awt.event.KeyAdapter() {

            public void keyTyped(java.awt.event.KeyEvent evt) {
                splitSizeTextFieldKeyTyped(evt);
            }
        });
        splitSizeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "MB", "KB", "bytes" }));
        splitSizeComboBox.setToolTipText("Careful! If you are not sure, select split by parts instead.");
        splitSizeComboBox.setEnabled(false);
        splitSizeComboBox.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                splitSizeComboBoxActionPerformed(evt);
            }
        });
        javax.swing.GroupLayout splitterPanelLayout = new javax.swing.GroupLayout(splitterPanel);
        splitterPanel.setLayout(splitterPanelLayout);
        splitterPanelLayout.setHorizontalGroup(splitterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(splitterPanelLayout.createSequentialGroup().addContainerGap().addGroup(splitterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(splitterPanelLayout.createSequentialGroup().addComponent(partsRadioButton).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(noofpartsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE).addGap(18, 18, 18).addComponent(sizeRadioButton).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(splitSizeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(splitSizeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addContainerGap()).addGroup(splitterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(splitterPanelLayout.createSequentialGroup().addComponent(splitterSelectFilePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addContainerGap()).addComponent(splitterCheckBox).addGroup(javax.swing.GroupLayout.Alignment.TRAILING, splitterPanelLayout.createSequentialGroup().addComponent(splitterSplitButton).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(splitterCancelButton).addContainerGap()).addGroup(splitterPanelLayout.createSequentialGroup().addComponent(splitterProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, 625, Short.MAX_VALUE).addContainerGap())))));
        splitterPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] { splitterCancelButton, splitterSplitButton });
        splitterPanelLayout.setVerticalGroup(splitterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(splitterPanelLayout.createSequentialGroup().addContainerGap().addComponent(splitterSelectFilePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addGroup(splitterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(partsRadioButton).addComponent(sizeRadioButton).addComponent(splitSizeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(noofpartsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(splitSizeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)).addGap(21, 21, 21).addComponent(splitterProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addGroup(splitterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(splitterSplitButton).addComponent(splitterCancelButton)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE).addComponent(splitterCheckBox).addContainerGap()));
        jTabbedPane1.addTab("<html><br /><br />Rozdělovač<br /><br />&nbsp;</html>", splitterPanel);
        aboutLabel.setFont(new java.awt.Font("Arial", 0, 18));
        aboutLabel.setText("O programu");
        aboutProductPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Produkt"));
        aboutLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jjsplit/resources/smalllogo.png")));
        aboutLogo.setToolTipText("Open Source File Splitter and Joiner");
        aboutJJSplitLabel.setFont(new java.awt.Font("Arial", 1, 14));
        aboutJJSplitLabel.setText("JJSplit");
        aboutJJSplitLabel.setToolTipText("Open Source File Splitter and Joiner");
        aboutVersionLabel.setText("v1.23");
        aboutLicenceLabel.setText("Licence: Public Domain");
        aboutLicenceLabel.setToolTipText("Public Domain means anybody can do damn anything to the code as if they are the owner.");
        aboutDescLabel.setText("Na uvedených stránkách můžete stahovat nejnovější verze, hlásit chyby a navrhovat rozšíření ^_^");
        aboutProductSiteLabel.setText("<html><a href=http://jjsplit.sf.net>http://jjsplit.sf.net</a></html>");
        aboutProductSiteLabel.setToolTipText("Click here to visit this site for updates..");
        aboutProductSiteLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        aboutProductSiteLabel.addMouseListener(new java.awt.event.MouseAdapter() {

            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aboutProductSiteLabelMouseClicked(evt);
            }
        });
        javax.swing.GroupLayout aboutProductPanelLayout = new javax.swing.GroupLayout(aboutProductPanel);
        aboutProductPanel.setLayout(aboutProductPanelLayout);
        aboutProductPanelLayout.setHorizontalGroup(aboutProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(aboutProductPanelLayout.createSequentialGroup().addContainerGap().addGroup(aboutProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(aboutProductPanelLayout.createSequentialGroup().addGap(10, 10, 10).addComponent(aboutProductSiteLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)).addGroup(aboutProductPanelLayout.createSequentialGroup().addComponent(aboutLogo).addGap(18, 18, 18).addGroup(aboutProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(aboutProductPanelLayout.createSequentialGroup().addComponent(aboutJJSplitLabel).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(aboutVersionLabel)).addGroup(aboutProductPanelLayout.createSequentialGroup().addGap(10, 10, 10).addComponent(aboutLicenceLabel)))).addComponent(aboutDescLabel)).addContainerGap(114, Short.MAX_VALUE)));
        aboutProductPanelLayout.setVerticalGroup(aboutProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(aboutProductPanelLayout.createSequentialGroup().addGroup(aboutProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(aboutLogo).addGroup(aboutProductPanelLayout.createSequentialGroup().addContainerGap().addGroup(aboutProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(aboutJJSplitLabel).addComponent(aboutVersionLabel)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(aboutLicenceLabel))).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(aboutDescLabel).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(aboutProductSiteLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addContainerGap(14, Short.MAX_VALUE)));
        aboutAuthorLabel.setBorder(javax.swing.BorderFactory.createTitledBorder("Autor"));
        aboutNameLabel.setText("Jméno:");
        aboutEmailLabel.setText("Email:");
        aboutTwitterLabel.setText("Následujte:");
        aboutMyName.setText("Vigneshwaran Raveendran");
        aboutMyEmail.setText("vigneshwaran2007@gmail.com");
        aboutMyEmail.setToolTipText("If you have complaints, mail me.");
        aboutMyTwitter.setText("<html><a href=\"http://twitter.com/vigneshwaranr\">@vigneshwaranr</a></html>");
        aboutMyTwitter.setToolTipText("Click here to visit my Twitter Profile...");
        aboutMyTwitter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        aboutMyTwitter.addMouseListener(new java.awt.event.MouseAdapter() {

            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aboutMyTwitterMouseClicked(evt);
            }
        });
        translationPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Překlad EN -> CZ"));
        translationPanel.setLayout(new java.awt.BorderLayout());
        translationNameLabel.setText("Jméno:Martin Průcha");
        translationPanel.add(translationNameLabel, java.awt.BorderLayout.CENTER);
        translationEmailLabel.setText("Email: prucha.martin@gmail.com");
        translationPanel.add(translationEmailLabel, java.awt.BorderLayout.PAGE_END);
        javax.swing.GroupLayout aboutAuthorLabelLayout = new javax.swing.GroupLayout(aboutAuthorLabel);
        aboutAuthorLabel.setLayout(aboutAuthorLabelLayout);
        aboutAuthorLabelLayout.setHorizontalGroup(aboutAuthorLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(aboutAuthorLabelLayout.createSequentialGroup().addContainerGap().addGroup(aboutAuthorLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(aboutTwitterLabel, javax.swing.GroupLayout.Alignment.TRAILING).addComponent(aboutEmailLabel, javax.swing.GroupLayout.Alignment.TRAILING).addComponent(aboutNameLabel, javax.swing.GroupLayout.Alignment.TRAILING)).addGap(18, 18, 18).addGroup(aboutAuthorLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(aboutMyEmail).addComponent(aboutMyTwitter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(aboutMyName)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 205, Short.MAX_VALUE).addComponent(translationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)));
        aboutAuthorLabelLayout.setVerticalGroup(aboutAuthorLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aboutAuthorLabelLayout.createSequentialGroup().addGroup(aboutAuthorLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(aboutNameLabel).addComponent(aboutMyName, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(aboutAuthorLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(aboutEmailLabel).addComponent(aboutMyEmail)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addGroup(aboutAuthorLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(aboutTwitterLabel).addComponent(aboutMyTwitter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)).addContainerGap()).addComponent(translationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE));
        javax.swing.GroupLayout aboutPanelLayout = new javax.swing.GroupLayout(aboutPanel);
        aboutPanel.setLayout(aboutPanelLayout);
        aboutPanelLayout.setHorizontalGroup(aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(aboutPanelLayout.createSequentialGroup().addGroup(aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(aboutPanelLayout.createSequentialGroup().addGap(20, 20, 20).addGroup(aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(aboutAuthorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addComponent(aboutProductPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))).addGroup(aboutPanelLayout.createSequentialGroup().addContainerGap().addComponent(aboutLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 625, Short.MAX_VALUE))).addContainerGap()));
        aboutPanelLayout.setVerticalGroup(aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(aboutPanelLayout.createSequentialGroup().addContainerGap().addComponent(aboutLabel).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(aboutProductPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(aboutAuthorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addContainerGap(12, Short.MAX_VALUE)));
        jTabbedPane1.addTab("<html><br /><br />O programu<br /><br />&nbsp;</html>", aboutPanel);
        statusPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        status.setText("Vyberte záložku \"Rozdělovač\" pro operaci rozdělení nebo záložku \"Slučovač\" pro operaci sloučení..");
        status.setToolTipText("Status Bar");
        javax.swing.GroupLayout statusPanelLayout = new javax.swing.GroupLayout(statusPanel);
        statusPanel.setLayout(statusPanelLayout);
        statusPanelLayout.setHorizontalGroup(statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(status, javax.swing.GroupLayout.DEFAULT_SIZE, 739, Short.MAX_VALUE));
        statusPanelLayout.setVerticalGroup(statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(status, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 14, Short.MAX_VALUE));
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(topPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addGroup(layout.createSequentialGroup().addContainerGap().addComponent(jTabbedPane1).addContainerGap()).addComponent(statusPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addComponent(topPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE).addGap(18, 18, 18).addComponent(statusPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)));
        pack();
    }

    private void joinerInputFileTextFieldMouseClicked(java.awt.event.MouseEvent evt) {
        joinerSelectFileButtonActionPerformed(null);
    }

    private void joinerOutputFileTextFieldMouseClicked(java.awt.event.MouseEvent evt) {
        joinerSelectOutputDirButtonActionPerformed(null);
    }

    private void joinerSelectFileButtonActionPerformed(java.awt.event.ActionEvent evt) {
        JFileChooser f = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("soubory JJSplit (.v1, .001)", "v1", "001");
        f.setFileFilter(filter);
        f.setAcceptAllFileFilterUsed(false);
        f.showOpenDialog(this);
        if (f.getSelectedFile() == null) return;
        joinerOutputFile = joinerInputFile = f.getSelectedFile();
        joinerInputFileTextField.setText(joinerInputFile + "");
        if ((joinerInputFile + "").endsWith(".v1")) joinerOutputFileName = joinerInputFile.getName().substring(0, joinerInputFile.getName().length() - 3); else joinerOutputFileName = joinerInputFile.getName().substring(0, joinerInputFile.getName().length() - 4);
        joinerOutputFileTextField.setText(joinerInputFile.getParent() + File.separator + joinerOutputFileName);
        joinerProgressBar.setValue(0);
        status.setText("Slučovač: První část vybrána..");
    }

    private void joinerSelectOutputDirButtonActionPerformed(java.awt.event.ActionEvent evt) {
        if (joinerInputFile == null) {
            JOptionPane.showMessageDialog(this, "Vyberte nejprve vstupní soubor!", "Oops", JOptionPane.WARNING_MESSAGE);
            status.setText("Slučovač: Vyberte nejprve vstupní soubor!");
            return;
        }
        JFileChooser f = new JFileChooser();
        f.setApproveButtonText("Vybrat umístění");
        f.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        f.showOpenDialog(this);
        if (f.getSelectedFile() != null) {
            joinerOutputFileTextField.setText(f.getSelectedFile() + File.separator + joinerOutputFileName);
            joinerOutputFile = new File(f.getSelectedFile() + File.separator + joinerInputFile.getName());
            status.setText("Slučovač: Výstupní adresář pro umístění sloučeného souboru byl změněn..");
        }
    }

    private void joinerJoinButtonActionPerformed(java.awt.event.ActionEvent evt) {
        if (new File(joinerOutputFileTextField.getText()).exists()) {
            JOptionPane.showMessageDialog(this, "Výstupní soubor již existuje!", "Oops", JOptionPane.ERROR_MESSAGE);
            status.setText("Slučovač: Výstupní soubor již existuje, zkuste změnit výstupní adresář..");
            return;
        }
        if (joinerCheckBox.isSelected()) {
            deleteFilesAfterJoin = true;
            status.setText("Slučovač: Poznámka- Části budou smazány jedna po druhé během slučování..");
        }
        if ((joinerInputFile + "").endsWith(".v1")) new Joiner(joinerInputFile, joinerOutputFile, joinerProgressBar, status, deleteFilesAfterJoin); else new JPfmJoiner(joinerInputFile, joinerOutputFile, joinerProgressBar, status, deleteFilesAfterJoin);
    }

    private void joinerCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {
        System.exit(0);
    }

    private void splitterInputFileTextFieldMouseClicked(java.awt.event.MouseEvent evt) {
        splitterSelectFileButtonActionPerformed(null);
    }

    private void splitterOutputFileTextFieldMouseClicked(java.awt.event.MouseEvent evt) {
        splitterSelectOutputDirButtonActionPerformed(null);
    }

    private void splitterSelectFileButtonActionPerformed(java.awt.event.ActionEvent evt) {
        JFileChooser f = new JFileChooser();
        f.showOpenDialog(this);
        if (f.getSelectedFile() == null) return;
        splitterOutputFile = splitterInputFile = f.getSelectedFile();
        splitterInputFileTextField.setText(splitterInputFile + "");
        splitterOutputFileTextField.setText(splitterInputFile + ".v1");
        splitterProgressBar.setValue(0);
        filesize = splitterInputFile.length();
        status.setText("Rozdělovač: Velikost vstupního souboru je " + Joiner.getSize(filesize));
        setSplitSize();
    }

    private void splitterSelectOutputDirButtonActionPerformed(java.awt.event.ActionEvent evt) {
        if (splitterInputFile == null) {
            JOptionPane.showMessageDialog(this, "Vyberte nejprve vstupní soubor!", "Oops", JOptionPane.WARNING_MESSAGE);
            status.setText("Rozdělovač: Vyberte nejprve vstupní soubor!");
            return;
        }
        JFileChooser f = new JFileChooser(splitterOutputFile);
        f.setApproveButtonText("Select location");
        f.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        f.showOpenDialog(this);
        if (f.getSelectedFile() != null) {
            splitterOutputFileTextField.setText(f.getSelectedFile() + File.separator + splitterInputFile.getName() + ".v1");
            splitterOutputFile = new File(f.getSelectedFile() + File.separator + splitterInputFile.getName());
            status.setText("Rozdělovač: Výstupní adresář pro umístění částí rozděleného souboru byl změněn..");
        }
    }

    private void splitterSplitButtonActionPerformed(java.awt.event.ActionEvent evt) {
        if (splitterCheckBox.isSelected()) {
            deleteFileAfterSplit = true;
            status.setText("Rozdělovač: Poznámka- Původní soubor bude po rozdělení smazán..");
        }
        try {
            if (partsRadioButton.isSelected()) {
                setSplitSize();
                if (noofparts < 2) {
                    JOptionPane.showMessageDialog(this, "Počet částí musí být alespoň 2!", "Oops", JOptionPane.WARNING_MESSAGE);
                    return;
                }
                new SplitterByParts(splitterInputFile, splitterOutputFile, noofparts, splitterProgressBar, status, deleteFileAfterSplit);
            } else {
                if (splitsize > filesize) {
                    JOptionPane.showMessageDialog(this, "Velikosti jednotlivých částí rozděleného souboru musí být menší než původní velikost souboru! *uff..*", "Oops", JOptionPane.WARNING_MESSAGE);
                    return;
                }
                setNoOfParts();
                new SplitterBySize(splitterInputFile, splitterOutputFile, splitsize, splitterProgressBar, status, deleteFileAfterSplit);
            }
        } catch (Exception ex) {
        }
    }

    private void splitterCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {
        System.exit(0);
    }

    private void partsRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {
        noofpartsTextField.setEnabled(true);
        splitSizeTextField.setEnabled(false);
        splitSizeComboBox.setEnabled(false);
        status.setText("Rozdělovač: Zvolil jste rozdělení souboru do specifikovaného počtu částí..");
    }

    private void sizeRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {
        noofpartsTextField.setEnabled(false);
        splitSizeTextField.setEnabled(true);
        splitSizeComboBox.setEnabled(true);
        status.setText("Rozdělovač: Zvolil jste rozdělení souboru do částí specifikované velikosti..");
    }

    private void splitSizeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {
        if (splitterInputFile == null) JOptionPane.showMessageDialog(this, "Vyberte nejprve vstupní soubor!", "Oops", JOptionPane.WARNING_MESSAGE);
    }

    private void splitSizeTextFieldKeyTyped(java.awt.event.KeyEvent evt) {
        textFieldValidator(evt);
        setNoOfParts();
    }

    private void noofpartsTextFieldKeyTyped(java.awt.event.KeyEvent evt) {
        textFieldValidator(evt);
        setSplitSize();
    }

    private void aboutProductSiteLabelMouseClicked(java.awt.event.MouseEvent evt) {
        if (!Desktop.isDesktopSupported()) return;
        try {
            Desktop.getDesktop().browse(new URI("http://sourceforge.net/projects/jjsplit"));
        } catch (URISyntaxException ex) {
            Logger.getLogger(JJSplit.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(JJSplit.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void aboutMyTwitterMouseClicked(java.awt.event.MouseEvent evt) {
        if (!Desktop.isDesktopSupported()) return;
        try {
            Desktop.getDesktop().browse(new URI("http://twitter.com/vigneshwaranr"));
        } catch (URISyntaxException ex) {
            Logger.getLogger(JJSplit.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(JJSplit.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception ex) {
        }
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new JJSplit().setVisible(true);
            }
        });
    }

    private void textFieldValidator(java.awt.event.KeyEvent evt) {
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c == java.awt.event.KeyEvent.VK_BACK_SPACE) || (c == java.awt.event.KeyEvent.VK_DELETE))) {
            getToolkit().beep();
            evt.consume();
        }
        if (splitterInputFile == null) {
            JOptionPane.showMessageDialog(this, "Vyberte nejprve vstupní soubor!", "Oops", JOptionPane.WARNING_MESSAGE);
            evt.consume();
        }
    }

    private void setSplitSize() {
        if (!noofpartsTextField.getText().equals("")) noofparts = Integer.parseInt(noofpartsTextField.getText());
        long filesize = splitterInputFile.length() / noofparts;
        if (filesize >= 1048576) {
            splitSizeComboBox.setSelectedItem("MB");
            splitSizeTextField.setText((filesize / 1048576) + "");
        } else if (filesize >= 1024) {
            splitSizeComboBox.setSelectedItem("KB");
            splitSizeTextField.setText((filesize / 1024) + "");
        } else {
            splitSizeComboBox.setSelectedItem("bajtů");
            splitSizeTextField.setText(filesize + "");
        }
    }

    private void setNoOfParts() {
        if (splitSizeTextField.getText().equals("")) return;
        if (splitSizeComboBox.getSelectedItem().equals("MB")) splitsize = Integer.parseInt(splitSizeTextField.getText()) * 1048576; else if (splitSizeComboBox.getSelectedItem().equals("KB")) splitsize = Integer.parseInt(splitSizeTextField.getText()) * 1024; else splitsize = Integer.parseInt(splitSizeTextField.getText());
        noofparts = (int) ((splitterInputFile.length() % splitsize == 0) ? (splitterInputFile.length() / splitsize) : (splitterInputFile.length() / splitsize) + 1);
        noofpartsTextField.setText(noofparts + "");
    }

    private javax.swing.JPanel aboutAuthorLabel;

    private javax.swing.JLabel aboutDescLabel;

    private javax.swing.JLabel aboutEmailLabel;

    private javax.swing.JLabel aboutJJSplitLabel;

    private javax.swing.JLabel aboutLabel;

    private javax.swing.JLabel aboutLicenceLabel;

    private javax.swing.JLabel aboutLogo;

    private javax.swing.JLabel aboutMyEmail;

    private javax.swing.JLabel aboutMyName;

    private javax.swing.JLabel aboutMyTwitter;

    private javax.swing.JLabel aboutNameLabel;

    private javax.swing.JPanel aboutPanel;

    private javax.swing.JPanel aboutProductPanel;

    private javax.swing.JLabel aboutProductSiteLabel;

    private javax.swing.JLabel aboutTwitterLabel;

    private javax.swing.JLabel aboutVersionLabel;

    private javax.swing.ButtonGroup buttonGroup1;

    private javax.swing.JTabbedPane jTabbedPane1;

    private javax.swing.JButton joinerCancelButton;

    private javax.swing.JCheckBox joinerCheckBox;

    private javax.swing.JTextField joinerInputFileTextField;

    private javax.swing.JButton joinerJoinButton;

    private javax.swing.JTextField joinerOutputFileTextField;

    private javax.swing.JPanel joinerPanel;

    private javax.swing.JProgressBar joinerProgressBar;

    private javax.swing.JButton joinerSelectFileButton;

    private javax.swing.JPanel joinerSelectFilePanel;

    private javax.swing.JButton joinerSelectOutputDirButton;

    private javax.swing.JLabel logo;

    private javax.swing.JTextField noofpartsTextField;

    private javax.swing.JRadioButton partsRadioButton;

    private javax.swing.JRadioButton sizeRadioButton;

    private javax.swing.JComboBox splitSizeComboBox;

    private javax.swing.JTextField splitSizeTextField;

    private javax.swing.JButton splitterCancelButton;

    private javax.swing.JCheckBox splitterCheckBox;

    private javax.swing.JTextField splitterInputFileTextField;

    private javax.swing.JTextField splitterOutputFileTextField;

    private javax.swing.JPanel splitterPanel;

    private javax.swing.JProgressBar splitterProgressBar;

    private javax.swing.JButton splitterSelectFileButton;

    private javax.swing.JPanel splitterSelectFilePanel;

    private javax.swing.JButton splitterSelectOutputDirButton;

    private javax.swing.JButton splitterSplitButton;

    private javax.swing.JLabel status;

    private javax.swing.JPanel statusPanel;

    private javax.swing.JLabel titleLabel;

    private javax.swing.JLabel topDescription;

    private javax.swing.JPanel topPanel;

    private javax.swing.JLabel translationEmailLabel;

    private javax.swing.JLabel translationNameLabel;

    private javax.swing.JPanel translationPanel;

    private javax.swing.JLabel version;
}
